services:
  powerdns:
    image: pschiffe/pdns-pgsql:4.9-alpine
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8081:8081
    environment:
      PDNS_local_address: '0.0.0.0, ::'
      PDNS_local_port: 53
      # API
      PDNS_api: yes
      PDNS_api_key: secret_api_key
      PDNS_webserver: no
      PDNS_webserver_port: 8081
      PDNS_webserver_address: 0.0.0.0
      PDNS_webserver_allow_from: '0.0.0.0/0,::/0'
      # DB
      PDNS_gpgsql_host: postgres
      PDNS_gpgsql_port: 5432
      PDNS_gpgsql_user: postgres
      PDNS_gpgsql_password: postgres
      PDNS_gpgsql_dbname: powerdns
      PDNS_gpgsql_dnssec: yes
    restart: on-failure:3

  powerdns-admin:
    image: powerdnsadmin/pda-legacy:v0.4.2
    profiles: [primary, development]
    environment:
      PDNS_API_URL: http://powerdns:8081/
      SECRET_KEY: secret_api_key
      PDNS_API_KEY: secret_api_key
      CSRF_COOKIE_SECURE: true
      LOCAL_DB_ENABLED: true
      SIGNUP_ENABLED: true
    ports:
      - 8091:80
    volumes:
      - powerdns-admin-data:/data
    depends_on:
      - powerdns
    restart: on-failure:3

  postgres:
    image: postgres:16.3-alpine
    profiles: [development]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  powerdns-admin-data:
    driver: local
  postgres-data:
    driver: local

